#!/usr/bin/env ruby

require "bundler"
Bundler.require :console
$:.unshift File.expand_path("../../test/lib", __FILE__)

puts "Loading MotionBundler development environment (#{MotionBundler::VERSION})"
Pry.start