# -*- coding: utf-8 -*-
$:.unshift "/Library/RubyMotion/lib"
require "motion/project"

# Require and prepare Bundler
require "bundler"
Bundler.require

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = "SampleApp"
end

# Track and specify files and their mutual dependencies within the :motion Bundler group
MotionBundler.setup do |app|
  app.require "stringio"
  app.require "strscan"
  app.require "zlib"
end